/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import static java.lang.String.valueOf;
import javax.swing.JFrame;

/**
 *
 * @author imamah
 */
public class Unstiched extends javax.swing.JFrame {
String loggedIn;
    /**
     * Creates new form Unstiched
     */
    public Unstiched(String email) {
         setVisible(true);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        initComponents();
        this.loggedIn=email;
          Clothes product=new Clothes();
      
        Item1Price.setText(valueOf(product.getProductPrice(1)));
        Item2Price.setText(valueOf(product.getProductPrice(2)));
        Item3Price.setText(valueOf(product.getProductPrice(3)));
        Item4Price.setText(valueOf(product.getProductPrice(4)));
      
       Cart c=new Cart();
        int count = c.getTotalItemsInCart(email);
           displayCountOfItems.setText(valueOf(count));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        Item1Price = new javax.swing.JLabel();
        Item2Price = new javax.swing.JLabel();
        Item3Price = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Item4Price = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        displayCountOfItems = new javax.swing.JLabel();
        HomeButton = new javax.swing.JLabel();
        MyProfile = new javax.swing.JLabel();
        LogOut = new javax.swing.JLabel();
        HomeButton1 = new javax.swing.JLabel();
        PlaceOrder = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(176, 233, 225));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 51, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 660));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 48)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/sapphire_logo.png"))); // NOI18N
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 420, 70));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 51, 738, 90));

        jPanel4.setBackground(new java.awt.Color(36, 47, 55));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Sapphire's latest unstitched looks hot off the press: discover a mélange of looks for every mood.");
        jPanel4.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 710, 40));

        jLabel21.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("UNSTITCHED");
        jPanel4.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 280, 40));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 143, 730, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/lawn1.PNG"))); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 198, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/lawn3.PNG"))); // NOI18N
        jLabel3.setOpaque(true);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(486, 50, -1, 296));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 225, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 191, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(922, 50, -1, -1));

        Item1Price.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Item1Price.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Item1Price.setText("Rs. 5,999");
        jPanel2.add(Item1Price, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 355, 103, 29));

        Item2Price.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Item2Price.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Item2Price.setText("Rs. 4,250");
        jPanel2.add(Item2Price, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 360, 103, -1));

        Item3Price.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Item3Price.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Item3Price.setText("Rs. 3,999");
        jPanel2.add(Item3Price, new org.netbeans.lib.awtextra.AbsoluteConstraints(541, 357, 103, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/lawn4.PNG"))); // NOI18N
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 444, 209, 284));

        Item4Price.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Item4Price.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Item4Price.setText("Rs. 6,999");
        jPanel2.add(Item4Price, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 734, 103, 29));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/commerce-and-shopping (2).png"))); // NOI18N
        jLabel14.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 390, 45, 36));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/commerce-and-shopping (2).png"))); // NOI18N
        jLabel15.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 390, 45, 36));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/commerce-and-shopping (2).png"))); // NOI18N
        jLabel18.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel18MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 769, 45, 36));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/commerce-and-shopping (2).png"))); // NOI18N
        jLabel19.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel19MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 390, 45, 36));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/lawn2.PNG"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 50, -1, 296));

        jScrollPane1.setViewportView(jPanel2);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 233, 730, 427));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        displayCountOfItems.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        displayCountOfItems.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/cart1.png"))); // NOI18N
        displayCountOfItems.setText("0");

        HomeButton.setBackground(new java.awt.Color(255, 255, 255));
        HomeButton.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        HomeButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        HomeButton.setText("Track Order");
        HomeButton.setOpaque(true);
        HomeButton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                HomeButtonMouseMoved(evt);
            }
        });
        HomeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeButtonMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                HomeButtonMouseExited(evt);
            }
        });

        MyProfile.setBackground(new java.awt.Color(255, 255, 255));
        MyProfile.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        MyProfile.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MyProfile.setText("My Profile");
        MyProfile.setOpaque(true);
        MyProfile.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                MyProfileMouseMoved(evt);
            }
        });
        MyProfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MyProfileMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MyProfileMouseExited(evt);
            }
        });

        LogOut.setBackground(new java.awt.Color(255, 255, 255));
        LogOut.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        LogOut.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LogOut.setText("Log Out");
        LogOut.setOpaque(true);
        LogOut.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                LogOutMouseMoved(evt);
            }
        });
        LogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogOutMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LogOutMouseExited(evt);
            }
        });

        HomeButton1.setBackground(new java.awt.Color(255, 255, 255));
        HomeButton1.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        HomeButton1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        HomeButton1.setText("Home");
        HomeButton1.setOpaque(true);
        HomeButton1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                HomeButton1MouseMoved(evt);
            }
        });
        HomeButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeButton1MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                HomeButton1MouseExited(evt);
            }
        });

        PlaceOrder.setBackground(new java.awt.Color(255, 255, 255));
        PlaceOrder.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        PlaceOrder.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PlaceOrder.setText("Place Order");
        PlaceOrder.setOpaque(true);
        PlaceOrder.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                PlaceOrderMouseMoved(evt);
            }
        });
        PlaceOrder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PlaceOrderMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PlaceOrderMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(286, Short.MAX_VALUE)
                .addComponent(HomeButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MyProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PlaceOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(HomeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(displayCountOfItems, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(displayCountOfItems, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HomeButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HomeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PlaceOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MyProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 800, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HomeButtonMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeButtonMouseMoved
        // TODO add your handling code here:
        HomeButton.setBackground(new java.awt.Color(176,233,225));
    }//GEN-LAST:event_HomeButtonMouseMoved

    private void HomeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeButtonMouseClicked
        // TODO add your handling code here:
        setVisible(false);
        TrackOrder track=new TrackOrder(loggedIn);
    }//GEN-LAST:event_HomeButtonMouseClicked

    private void HomeButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeButtonMouseExited
        // TODO add your handling code here:

        HomeButton.setBackground(new java.awt.Color(255,255,255));
    }//GEN-LAST:event_HomeButtonMouseExited

    private void MyProfileMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MyProfileMouseMoved
        // TODO add your handling code here:
        MyProfile.setBackground(new java.awt.Color(176,233,225));
    }//GEN-LAST:event_MyProfileMouseMoved

    private void MyProfileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MyProfileMouseClicked
        // TODO add your handling code here:
        setVisible(false);
      Profile profile=new Profile(loggedIn);
    }//GEN-LAST:event_MyProfileMouseClicked

    private void MyProfileMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MyProfileMouseExited
        // TODO add your handling code here:
        MyProfile.setBackground(new java.awt.Color(255,255,255));
    }//GEN-LAST:event_MyProfileMouseExited

    private void LogOutMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogOutMouseMoved
        // TODO add your handling code here:
        LogOut.setBackground(new java.awt.Color(176,233,225));
    }//GEN-LAST:event_LogOutMouseMoved

    private void LogOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogOutMouseClicked
        // TODO add your handling code here:
        setVisible(false);
        signin signIn = new signin();
    }//GEN-LAST:event_LogOutMouseClicked

    private void LogOutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogOutMouseExited
        // TODO add your handling code here:
        LogOut.setBackground(new java.awt.Color(255,255,255));
    }//GEN-LAST:event_LogOutMouseExited

    private void HomeButton1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeButton1MouseMoved
        // TODO add your handling code here:
       HomeButton1.setBackground(new java.awt.Color(176,233,225));
    }//GEN-LAST:event_HomeButton1MouseMoved

    private void HomeButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeButton1MouseClicked
        // TODO add your handling code here:
        setVisible(false);
     HomePage homePage=new HomePage(loggedIn);
    }//GEN-LAST:event_HomeButton1MouseClicked

    private void HomeButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeButton1MouseExited
        // TODO add your handling code here:
        HomeButton1.setBackground(new java.awt.Color(255,255,255));
    }//GEN-LAST:event_HomeButton1MouseExited

    private void PlaceOrderMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PlaceOrderMouseMoved
        // TODO add your handling code here:
        PlaceOrder.setBackground(new java.awt.Color(176,233,225));
    }//GEN-LAST:event_PlaceOrderMouseMoved

    private void PlaceOrderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PlaceOrderMouseClicked
        // TODO add your handling code here:
        setVisible(false);
        CheckOutOrder checkout=new CheckOutOrder(loggedIn);
    }//GEN-LAST:event_PlaceOrderMouseClicked

    private void PlaceOrderMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PlaceOrderMouseExited
        // TODO add your handling code here:
        PlaceOrder.setBackground(new java.awt.Color(255,255,255));
    }//GEN-LAST:event_PlaceOrderMouseExited

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        // TODO add your handling code here:
          Clothes product=new Clothes();
        product.getProduct(7);
          AddToCart addToCart=new AddToCart(product,loggedIn);
    }//GEN-LAST:event_jLabel14MouseClicked

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        // TODO add your handling code here:
               Clothes product=new Clothes();
        product.getProduct(8);
          AddToCart addToCart=new AddToCart(product,loggedIn);
    }//GEN-LAST:event_jLabel15MouseClicked

    private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseClicked
        // TODO add your handling code here:
               Clothes product=new Clothes();
        product.getProduct(9);
          AddToCart addToCart=new AddToCart(product,loggedIn);
    }//GEN-LAST:event_jLabel19MouseClicked

    private void jLabel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseClicked
        // TODO add your handling code here:
               Clothes product=new Clothes();
        product.getProduct(10);
          AddToCart addToCart=new AddToCart(product,loggedIn);
    }//GEN-LAST:event_jLabel18MouseClicked

 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel HomeButton;
    private javax.swing.JLabel HomeButton1;
    private javax.swing.JLabel Item1Price;
    private javax.swing.JLabel Item2Price;
    private javax.swing.JLabel Item3Price;
    private javax.swing.JLabel Item4Price;
    private javax.swing.JLabel LogOut;
    private javax.swing.JLabel MyProfile;
    private javax.swing.JLabel PlaceOrder;
    private javax.swing.JLabel displayCountOfItems;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
